# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _mirage_py
else:
    import _mirage_py

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

if _swig_python_version_info[0:2] >= (3, 3):
    import collections.abc
else:
    import collections

class ApplicationArgs(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    nCount = property(_mirage_py.ApplicationArgs_nCount_get, _mirage_py.ApplicationArgs_nCount_set)
    ppArgs = property(_mirage_py.ApplicationArgs_ppArgs_get, _mirage_py.ApplicationArgs_ppArgs_set)

    def __init__(self):
        _mirage_py.ApplicationArgs_swiginit(self, _mirage_py.new_ApplicationArgs())
    __swig_destroy__ = _mirage_py.delete_ApplicationArgs

# Register ApplicationArgs in _mirage_py:
_mirage_py.ApplicationArgs_swigregister(ApplicationArgs)
class ApplicationProps(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    strName = property(_mirage_py.ApplicationProps_strName_get, _mirage_py.ApplicationProps_strName_set)
    strWorkspaceDir = property(_mirage_py.ApplicationProps_strWorkspaceDir_get, _mirage_py.ApplicationProps_strWorkspaceDir_set)
    args = property(_mirage_py.ApplicationProps_args_get, _mirage_py.ApplicationProps_args_set)

    def __init__(self):
        _mirage_py.ApplicationProps_swiginit(self, _mirage_py.new_ApplicationProps())
    __swig_destroy__ = _mirage_py.delete_ApplicationProps

# Register ApplicationProps in _mirage_py:
_mirage_py.ApplicationProps_swigregister(ApplicationProps)
class Vertex(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    vPos = property(_mirage_py.Vertex_vPos_get, _mirage_py.Vertex_vPos_set)
    vColor = property(_mirage_py.Vertex_vColor_get, _mirage_py.Vertex_vColor_set)
    vUV = property(_mirage_py.Vertex_vUV_get, _mirage_py.Vertex_vUV_set)

    def __init__(self):
        _mirage_py.Vertex_swiginit(self, _mirage_py.new_Vertex())
    __swig_destroy__ = _mirage_py.delete_Vertex

# Register Vertex in _mirage_py:
_mirage_py.Vertex_swigregister(Vertex)
left = _mirage_py.left
right = _mirage_py.right
center = _mirage_py.center
class float_vec2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_mirage_py.float_vec2_x_get, _mirage_py.float_vec2_x_set)
    y = property(_mirage_py.float_vec2_y_get, _mirage_py.float_vec2_y_set)

    def __init__(self):
        _mirage_py.float_vec2_swiginit(self, _mirage_py.new_float_vec2())
    __swig_destroy__ = _mirage_py.delete_float_vec2

# Register float_vec2 in _mirage_py:
_mirage_py.float_vec2_swigregister(float_vec2)
class float_vec3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_mirage_py.float_vec3_x_get, _mirage_py.float_vec3_x_set)
    y = property(_mirage_py.float_vec3_y_get, _mirage_py.float_vec3_y_set)
    z = property(_mirage_py.float_vec3_z_get, _mirage_py.float_vec3_z_set)

    def __init__(self):
        _mirage_py.float_vec3_swiginit(self, _mirage_py.new_float_vec3())
    __swig_destroy__ = _mirage_py.delete_float_vec3

# Register float_vec3 in _mirage_py:
_mirage_py.float_vec3_swigregister(float_vec3)
class float_vec4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    r = property(_mirage_py.float_vec4_r_get, _mirage_py.float_vec4_r_set)
    g = property(_mirage_py.float_vec4_g_get, _mirage_py.float_vec4_g_set)
    b = property(_mirage_py.float_vec4_b_get, _mirage_py.float_vec4_b_set)
    a = property(_mirage_py.float_vec4_a_get, _mirage_py.float_vec4_a_set)

    def __init__(self):
        _mirage_py.float_vec4_swiginit(self, _mirage_py.new_float_vec4())
    __swig_destroy__ = _mirage_py.delete_float_vec4

# Register float_vec4 in _mirage_py:
_mirage_py.float_vec4_swigregister(float_vec4)
class int_vec2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_mirage_py.int_vec2_x_get, _mirage_py.int_vec2_x_set)
    y = property(_mirage_py.int_vec2_y_get, _mirage_py.int_vec2_y_set)

    def __init__(self):
        _mirage_py.int_vec2_swiginit(self, _mirage_py.new_int_vec2())
    __swig_destroy__ = _mirage_py.delete_int_vec2

# Register int_vec2 in _mirage_py:
_mirage_py.int_vec2_swigregister(int_vec2)
class int_vec3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_mirage_py.int_vec3_x_get, _mirage_py.int_vec3_x_set)
    y = property(_mirage_py.int_vec3_y_get, _mirage_py.int_vec3_y_set)
    z = property(_mirage_py.int_vec3_z_get, _mirage_py.int_vec3_z_set)

    def __init__(self):
        _mirage_py.int_vec3_swiginit(self, _mirage_py.new_int_vec3())
    __swig_destroy__ = _mirage_py.delete_int_vec3

# Register int_vec3 in _mirage_py:
_mirage_py.int_vec3_swigregister(int_vec3)
class int_vec4(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    r = property(_mirage_py.int_vec4_r_get, _mirage_py.int_vec4_r_set)
    g = property(_mirage_py.int_vec4_g_get, _mirage_py.int_vec4_g_set)
    b = property(_mirage_py.int_vec4_b_get, _mirage_py.int_vec4_b_set)
    a = property(_mirage_py.int_vec4_a_get, _mirage_py.int_vec4_a_set)

    def __init__(self):
        _mirage_py.int_vec4_swiginit(self, _mirage_py.new_int_vec4())
    __swig_destroy__ = _mirage_py.delete_int_vec4

# Register int_vec4 in _mirage_py:
_mirage_py.int_vec4_swigregister(int_vec4)

def vec2_float(x, y):
    vec2 = float_vec2()
    vec2.x = x
    vec2.y = y
    return vec2

def vec2_int(x, y):
    vec2 = int_vec2()
    vec3.x = x
    vec3.y = y
    return vec2

def vec3_float(x, y, z):
    vec3 = float_vec3()
    vec3.x = x
    vec3.y = y
    vec3.z = z
    return vec3

def vec3_int(x, y, z):
    vec3 = int_vec3()
    vec3.x = x
    vec3.y = y
    vec3.z = z
    return vec3

def vec4_float(r, g, b, a):
    vec4 = float_vec4()
    vec4.r = r
    vec4.g = g
    vec4.b = b
    vec4.a = a
    return vec4

def vec4_int(x, y, z):
    vec4 = int_vec4()
    vec4.r = r
    vec4.g = g
    vec4.b = b
    vec4.a = a
    return vec4


def main(argc, argv):
    return _mirage_py.main(argc, argv)

def Launch(upApp):
    return _mirage_py.Launch(upApp)
class BaseApp(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _mirage_py.delete_BaseApp

    def PushLayer(self, upLayer):
        return _mirage_py.BaseApp_PushLayer(self, upLayer)

    def PushOverlay(self, upLayer):
        return _mirage_py.BaseApp_PushOverlay(self, upLayer)
    def __disown__(self):
        self.this.disown()
        _mirage_py.disown_BaseApp(self)
        return weakref.proxy(self)

# Register BaseApp in _mirage_py:
_mirage_py.BaseApp_swigregister(BaseApp)
class BaseLayer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        if self.__class__ == BaseLayer:
            _self = None
        else:
            _self = self
        _mirage_py.BaseLayer_swiginit(self, _mirage_py.new_BaseLayer(_self, *args))
    __swig_destroy__ = _mirage_py.delete_BaseLayer

    def OnAttach(self):
        return _mirage_py.BaseLayer_OnAttach(self)

    def OnDetach(self):
        return _mirage_py.BaseLayer_OnDetach(self)

    def OnUpdate(self):
        return _mirage_py.BaseLayer_OnUpdate(self)

    def OnEvent(self, refEvent):
        return _mirage_py.BaseLayer_OnEvent(self, refEvent)
    def __disown__(self):
        self.this.disown()
        _mirage_py.disown_BaseLayer(self)
        return weakref.proxy(self)

# Register BaseLayer in _mirage_py:
_mirage_py.BaseLayer_swigregister(BaseLayer)
EventType_NONE = _mirage_py.EventType_NONE
EventType_KeyPressed = _mirage_py.EventType_KeyPressed
EventType_KeyReleased = _mirage_py.EventType_KeyReleased
EventType_KeyTyped = _mirage_py.EventType_KeyTyped
EventType_MouseMoved = _mirage_py.EventType_MouseMoved
EventType_MouseScrolled = _mirage_py.EventType_MouseScrolled
EventType_MouseButtonPressed = _mirage_py.EventType_MouseButtonPressed
EventType_MouseButtonReleased = _mirage_py.EventType_MouseButtonReleased
EventType_WindowClose = _mirage_py.EventType_WindowClose
EventType_WindowResize = _mirage_py.EventType_WindowResize
EventType_WindowFoucs = _mirage_py.EventType_WindowFoucs
EventType_WindowLostFocus = _mirage_py.EventType_WindowLostFocus
EventType_WindowMoved = _mirage_py.EventType_WindowMoved
EventType_AppTick = _mirage_py.EventType_AppTick
EventType_AppUpdate = _mirage_py.EventType_AppUpdate
EventType_AppRender = _mirage_py.EventType_AppRender
NONE = _mirage_py.NONE
EventCategoryApplication = _mirage_py.EventCategoryApplication
EventCategoryInput = _mirage_py.EventCategoryInput
EventCategoryKeyboard = _mirage_py.EventCategoryKeyboard
EventCategoryMouse = _mirage_py.EventCategoryMouse
EventCategoryMouseButton = _mirage_py.EventCategoryMouseButton
class BaseEvent(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _mirage_py.delete_BaseEvent

    def GetEventType(self):
        return _mirage_py.BaseEvent_GetEventType(self)

    def GetCategoryFlags(self):
        return _mirage_py.BaseEvent_GetCategoryFlags(self)

    def SetHandleStatus(self, bHandleStatus):
        return _mirage_py.BaseEvent_SetHandleStatus(self, bHandleStatus)

    def IsHandled(self):
        return _mirage_py.BaseEvent_IsHandled(self)

    def IsInCategory(self, category):
        return _mirage_py.BaseEvent_IsInCategory(self, category)

# Register BaseEvent in _mirage_py:
_mirage_py.BaseEvent_swigregister(BaseEvent)
Success = _mirage_py.Success
InvalidParam = _mirage_py.InvalidParam
OOM = _mirage_py.OOM
Failed = _mirage_py.Failed
Unsupported = _mirage_py.Unsupported
class AppDeleter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __call__(self, p):
        return _mirage_py.AppDeleter___call__(self, p)

    def __init__(self):
        _mirage_py.AppDeleter_swiginit(self, _mirage_py.new_AppDeleter())
    __swig_destroy__ = _mirage_py.delete_AppDeleter

# Register AppDeleter in _mirage_py:
_mirage_py.AppDeleter_swigregister(AppDeleter)
class Application(BaseApp):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, rProps):
        if self.__class__ == Application:
            _self = None
        else:
            _self = self
        _mirage_py.Application_swiginit(self, _mirage_py.new_Application(_self, rProps))
    __swig_destroy__ = _mirage_py.delete_Application

    def PushLayer(self, upLayer):
        return _mirage_py.Application_PushLayer(self, upLayer)

    def PushOverlay(self, upLayer):
        return _mirage_py.Application_PushOverlay(self, upLayer)
    def __disown__(self):
        self.this.disown()
        _mirage_py.disown_Application(self)
        return weakref.proxy(self)

# Register Application in _mirage_py:
_mirage_py.Application_swigregister(Application)
class Component(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.Component_swiginit(self, _mirage_py.new_Component())
    __swig_destroy__ = _mirage_py.delete_Component

# Register Component in _mirage_py:
_mirage_py.Component_swigregister(Component)
class AudioSource(Component):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, spData):
        _mirage_py.AudioSource_swiginit(self, _mirage_py.new_AudioSource(spData))
    __swig_destroy__ = _mirage_py.delete_AudioSource

    def SetPosition(self, rPos):
        return _mirage_py.AudioSource_SetPosition(self, rPos)

    def GetPosition(self):
        return _mirage_py.AudioSource_GetPosition(self)

    def SetAudioPitch(self, fPitch):
        return _mirage_py.AudioSource_SetAudioPitch(self, fPitch)

    def GetAudioPitch(self):
        return _mirage_py.AudioSource_GetAudioPitch(self)

    def SetAudioGain(self, fGain):
        return _mirage_py.AudioSource_SetAudioGain(self, fGain)

    def GetAudioGain(self):
        return _mirage_py.AudioSource_GetAudioGain(self)

    def SetVelocity(self, rVelocity):
        return _mirage_py.AudioSource_SetVelocity(self, rVelocity)

    def GetVelocity(self):
        return _mirage_py.AudioSource_GetVelocity(self)

    def SetLoopingStatus(self, bEnable):
        return _mirage_py.AudioSource_SetLoopingStatus(self, bEnable)

    def GetLoopingStatus(self):
        return _mirage_py.AudioSource_GetLoopingStatus(self)

    def PlayAudio(self):
        return _mirage_py.AudioSource_PlayAudio(self)

    def StopPlaying(self):
        return _mirage_py.AudioSource_StopPlaying(self)

    def PausePlaying(self):
        return _mirage_py.AudioSource_PausePlaying(self)

    def IsPlaying(self):
        return _mirage_py.AudioSource_IsPlaying(self)

    def SetBuffer(self, spBuffer):
        return _mirage_py.AudioSource_SetBuffer(self, spBuffer)

# Register AudioSource in _mirage_py:
_mirage_py.AudioSource_swigregister(AudioSource)
SHARED_PTR_DISOWN = _mirage_py.SHARED_PTR_DISOWN
class SharedAudioBuffer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.SharedAudioBuffer_swiginit(self, _mirage_py.new_SharedAudioBuffer())
    __swig_destroy__ = _mirage_py.delete_SharedAudioBuffer

# Register SharedAudioBuffer in _mirage_py:
_mirage_py.SharedAudioBuffer_swigregister(SharedAudioBuffer)
MRG_AUDIO_FORMAT_MONO8 = _mirage_py.MRG_AUDIO_FORMAT_MONO8
MRG_AUDIO_FORMAT_MONO16 = _mirage_py.MRG_AUDIO_FORMAT_MONO16
MRG_AUDIO_FORMAT_STEREO8 = _mirage_py.MRG_AUDIO_FORMAT_STEREO8
MRG_AUDIO_FORMAT_STEREO16 = _mirage_py.MRG_AUDIO_FORMAT_STEREO16
class AudioBuffer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _mirage_py.AudioBuffer_swiginit(self, _mirage_py.new_AudioBuffer(*args))
    __swig_destroy__ = _mirage_py.delete_AudioBuffer

# Register AudioBuffer in _mirage_py:
_mirage_py.AudioBuffer_swigregister(AudioBuffer)
class AudioListener(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def GetInstance():
        return _mirage_py.AudioListener_GetInstance()

    def SetGain(self, fGain):
        return _mirage_py.AudioListener_SetGain(self, fGain)

    def GetGain(self):
        return _mirage_py.AudioListener_GetGain(self)

    def SetPosition(self, rPosition):
        return _mirage_py.AudioListener_SetPosition(self, rPosition)

    def GetPosition(self):
        return _mirage_py.AudioListener_GetPosition(self)

    def SetVelocity(self, rVelocity):
        return _mirage_py.AudioListener_SetVelocity(self, rVelocity)

    def GetVelocity(self):
        return _mirage_py.AudioListener_GetVelocity(self)

    def SetFocusVector(self, rFocus):
        return _mirage_py.AudioListener_SetFocusVector(self, rFocus)

    def GetFocusVector(self):
        return _mirage_py.AudioListener_GetFocusVector(self)

    def SetTopVector(self, rTop):
        return _mirage_py.AudioListener_SetTopVector(self, rTop)

    def GetTopVector(self):
        return _mirage_py.AudioListener_GetTopVector(self)

# Register AudioListener in _mirage_py:
_mirage_py.AudioListener_swigregister(AudioListener)
class AudioUtils(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def LoadAudioBuffer(svFileName):
        return _mirage_py.AudioUtils_LoadAudioBuffer(svFileName)

    def __init__(self):
        _mirage_py.AudioUtils_swiginit(self, _mirage_py.new_AudioUtils())
    __swig_destroy__ = _mirage_py.delete_AudioUtils

# Register AudioUtils in _mirage_py:
_mirage_py.AudioUtils_swigregister(AudioUtils)
class Model(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.Model_swiginit(self, _mirage_py.new_Model())
    __swig_destroy__ = _mirage_py.delete_Model

    def Refresh(self):
        return _mirage_py.Model_Refresh(self)

    def SetLayer(self, uLayer):
        return _mirage_py.Model_SetLayer(self, uLayer)

    def GetLayer(self):
        return _mirage_py.Model_GetLayer(self)

    def SetPosition(self, rPosition, bOnOverlay=False):
        return _mirage_py.Model_SetPosition(self, rPosition, bOnOverlay)

    def GetPosition(self):
        return _mirage_py.Model_GetPosition(self)

    def SetRotation(self, rRot):
        return _mirage_py.Model_SetRotation(self, rRot)

    def GetRotation(self):
        return _mirage_py.Model_GetRotation(self)

    def GetScale(self):
        return _mirage_py.Model_GetScale(self)

    def SetScale(self, rScale):
        return _mirage_py.Model_SetScale(self, rScale)

    def SetMaterial(self, svMaterial):
        return _mirage_py.Model_SetMaterial(self, svMaterial)

    def SetMesh(self, svMesh, bIsStaic=True):
        return _mirage_py.Model_SetMesh(self, svMesh, bIsStaic)

    def CreateMesh(self, rVertexes, rVertexIndexes, bIsStatic=True):
        return _mirage_py.Model_CreateMesh(self, rVertexes, rVertexIndexes, bIsStatic)

    def SetVertexBoneMaps(self, rVertexBoneMaps):
        return _mirage_py.Model_SetVertexBoneMaps(self, rVertexBoneMaps)

    def Wakeup(self):
        return _mirage_py.Model_Wakeup(self)

    def SetCullFaceStatus(self, bEnable):
        return _mirage_py.Model_SetCullFaceStatus(self, bEnable)

    def Configure(self, uLayer, svMaterial, svMesh, bIsStatic=True):
        return _mirage_py.Model_Configure(self, uLayer, svMaterial, svMesh, bIsStatic)

    def AddTransform(self):
        return _mirage_py.Model_AddTransform(self)

    def AddMeshFilter(self):
        return _mirage_py.Model_AddMeshFilter(self)

    def AddMeshRenderer(self):
        return _mirage_py.Model_AddMeshRenderer(self)

    def AddCamera(self):
        return _mirage_py.Model_AddCamera(self)

    def AddAudioSource(self):
        return _mirage_py.Model_AddAudioSource(self)

    def AddAnimation(self):
        return _mirage_py.Model_AddAnimation(self)

    def GetTransform(self):
        return _mirage_py.Model_GetTransform(self)

    def GetMeshFilter(self):
        return _mirage_py.Model_GetMeshFilter(self)

    def GetMeshRenderer(self):
        return _mirage_py.Model_GetMeshRenderer(self)

    def GetCamera(self):
        return _mirage_py.Model_GetCamera(self)

    def GetAudioSource(self):
        return _mirage_py.Model_GetAudioSource(self)

    def GetAnimation(self):
        return _mirage_py.Model_GetAnimation(self)

    def AddEvent(self, *args):
        return _mirage_py.Model_AddEvent(self, *args)

# Register Model in _mirage_py:
_mirage_py.Model_swigregister(Model)
class UniqueTransform(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.UniqueTransform_swiginit(self, _mirage_py.new_UniqueTransform())
    __swig_destroy__ = _mirage_py.delete_UniqueTransform

# Register UniqueTransform in _mirage_py:
_mirage_py.UniqueTransform_swigregister(UniqueTransform)
class UniqueMeshFilter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.UniqueMeshFilter_swiginit(self, _mirage_py.new_UniqueMeshFilter())
    __swig_destroy__ = _mirage_py.delete_UniqueMeshFilter

# Register UniqueMeshFilter in _mirage_py:
_mirage_py.UniqueMeshFilter_swigregister(UniqueMeshFilter)
class UniqueMeshRenderer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.UniqueMeshRenderer_swiginit(self, _mirage_py.new_UniqueMeshRenderer())
    __swig_destroy__ = _mirage_py.delete_UniqueMeshRenderer

# Register UniqueMeshRenderer in _mirage_py:
_mirage_py.UniqueMeshRenderer_swigregister(UniqueMeshRenderer)
class UniqueCamera(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.UniqueCamera_swiginit(self, _mirage_py.new_UniqueCamera())
    __swig_destroy__ = _mirage_py.delete_UniqueCamera

# Register UniqueCamera in _mirage_py:
_mirage_py.UniqueCamera_swigregister(UniqueCamera)
class UniqueAudioSource(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.UniqueAudioSource_swiginit(self, _mirage_py.new_UniqueAudioSource())
    __swig_destroy__ = _mirage_py.delete_UniqueAudioSource

# Register UniqueAudioSource in _mirage_py:
_mirage_py.UniqueAudioSource_swigregister(UniqueAudioSource)
class UniqueAnimation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.UniqueAnimation_swiginit(self, _mirage_py.new_UniqueAnimation())
    __swig_destroy__ = _mirage_py.delete_UniqueAnimation

# Register UniqueAnimation in _mirage_py:
_mirage_py.UniqueAnimation_swigregister(UniqueAnimation)
class Button(Model):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.Button_swiginit(self, _mirage_py.new_Button())
    __swig_destroy__ = _mirage_py.delete_Button

    def SetLayer(self, uLayer):
        return _mirage_py.Button_SetLayer(self, uLayer)

    def SetSize(self, fWidth, fHeight):
        return _mirage_py.Button_SetSize(self, fWidth, fHeight)

    def SetScale(self, rScale):
        return _mirage_py.Button_SetScale(self, rScale)

    def SetPosition(self, rPosition, bOnOverlay=False):
        return _mirage_py.Button_SetPosition(self, rPosition, bOnOverlay)

    def Configure(self, *args):
        return _mirage_py.Button_Configure(self, *args)

    def FillButton(self, *args):
        return _mirage_py.Button_FillButton(self, *args)

    def SetTextColor(self, *args):
        return _mirage_py.Button_SetTextColor(self, *args)

    def Refresh(self):
        return _mirage_py.Button_Refresh(self)

    def SetClickCallback(self, *args):
        return _mirage_py.Button_SetClickCallback(self, *args)

# Register Button in _mirage_py:
_mirage_py.Button_swigregister(Button)
MRG_DEPTH_BUFFER_BIT = _mirage_py.MRG_DEPTH_BUFFER_BIT
MRG_STENCIL_BUFFER_BIT = _mirage_py.MRG_STENCIL_BUFFER_BIT
MRG_COLOR_BUFFER_BIT = _mirage_py.MRG_COLOR_BUFFER_BIT
class Camera(Component):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, spHandle):
        _mirage_py.Camera_swiginit(self, _mirage_py.new_Camera(spHandle))
    __swig_destroy__ = _mirage_py.delete_Camera

    def SetViewMat(self, rFocusVec, rTopVec):
        return _mirage_py.Camera_SetViewMat(self, rFocusVec, rTopVec)

    def SetProjectionMat(self, fFovDegress, fAspectRatio, fNearClip, fFarClip):
        return _mirage_py.Camera_SetProjectionMat(self, fFovDegress, fAspectRatio, fNearClip, fFarClip)

    def SetDepth(self, uDepth):
        return _mirage_py.Camera_SetDepth(self, uDepth)

    def SetClearFlag(self, uClearFlag):
        return _mirage_py.Camera_SetClearFlag(self, uClearFlag)

    def SetCullingMask(self, uCullingMask):
        return _mirage_py.Camera_SetCullingMask(self, uCullingMask)

    def EnableOrtho(self, fLeft, fRight, fTop, fBottom, fZNear, fZFar):
        return _mirage_py.Camera_EnableOrtho(self, fLeft, fRight, fTop, fBottom, fZNear, fZFar)

    def Clear(self):
        return _mirage_py.Camera_Clear(self)

    @staticmethod
    def Foreach(fnAction):
        return _mirage_py.Camera_Foreach(fnAction)

# Register Camera in _mirage_py:
_mirage_py.Camera_swigregister(Camera)
class TextureDeleter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __call__(self, p):
        return _mirage_py.TextureDeleter___call__(self, p)

    def __init__(self):
        _mirage_py.TextureDeleter_swiginit(self, _mirage_py.new_TextureDeleter())
    __swig_destroy__ = _mirage_py.delete_TextureDeleter

# Register TextureDeleter in _mirage_py:
_mirage_py.TextureDeleter_swigregister(TextureDeleter)
class Font(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, spData):
        _mirage_py.Font_swiginit(self, _mirage_py.new_Font(spData))
    __swig_destroy__ = _mirage_py.delete_Font

    def LoadChar(self, c):
        return _mirage_py.Font_LoadChar(self, c)

    def CreateTextTexture(self, *args):
        return _mirage_py.Font_CreateTextTexture(self, *args)

    def GetWidth(self):
        return _mirage_py.Font_GetWidth(self)

    def GetHeight(self):
        return _mirage_py.Font_GetHeight(self)

    def GetPitch(self):
        return _mirage_py.Font_GetPitch(self)

    def GetScanline(self):
        return _mirage_py.Font_GetScanline(self)

    @staticmethod
    def LoadFontFromFile(svFilePath, uFtSize):
        return _mirage_py.Font_LoadFontFromFile(svFilePath, uFtSize)

# Register Font in _mirage_py:
_mirage_py.Font_swigregister(Font)
class Image(Model):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.Image_swiginit(self, _mirage_py.new_Image())
    __swig_destroy__ = _mirage_py.delete_Image

    def SetLayer(self, uLayer):
        return _mirage_py.Image_SetLayer(self, uLayer)

    def GetLayer(self):
        return _mirage_py.Image_GetLayer(self)

    def SetMaterial(self, svMaterial):
        return _mirage_py.Image_SetMaterial(self, svMaterial)

    def FillColor(self, *args):
        return _mirage_py.Image_FillColor(self, *args)

    def SetSize(self, fWidth, fHeight):
        return _mirage_py.Image_SetSize(self, fWidth, fHeight)

    def SetScale(self, rScale):
        return _mirage_py.Image_SetScale(self, rScale)

    def SetPosition(self, rPosition, bOnOverlay=False):
        return _mirage_py.Image_SetPosition(self, rPosition, bOnOverlay)

    def Configure(self, nWidth, nHeight, uLayer, svMaterial):
        return _mirage_py.Image_Configure(self, nWidth, nHeight, uLayer, svMaterial)

    def AddMask(self, svMaterial, bEnable=False):
        return _mirage_py.Image_AddMask(self, svMaterial, bEnable)

    def IsMaskEnabled(self):
        return _mirage_py.Image_IsMaskEnabled(self)

    def DisableMask(self):
        return _mirage_py.Image_DisableMask(self)

    def EnableMask(self):
        return _mirage_py.Image_EnableMask(self)

    def SetMaskStatus(self, bEnable):
        return _mirage_py.Image_SetMaskStatus(self, bEnable)

    def IsDepthEnabled(self):
        return _mirage_py.Image_IsDepthEnabled(self)

    def SetDepthStatus(self, bEnable):
        return _mirage_py.Image_SetDepthStatus(self, bEnable)

    def Refresh(self):
        return _mirage_py.Image_Refresh(self)

# Register Image in _mirage_py:
_mirage_py.Image_swigregister(Image)
Button0 = _mirage_py.Button0
Button1 = _mirage_py.Button1
Button2 = _mirage_py.Button2
Button3 = _mirage_py.Button3
Button4 = _mirage_py.Button4
Button5 = _mirage_py.Button5
Button6 = _mirage_py.Button6
Button7 = _mirage_py.Button7
ButtonLast = _mirage_py.ButtonLast
ButtonLeft = _mirage_py.ButtonLeft
ButtonRight = _mirage_py.ButtonRight
ButtonMiddle = _mirage_py.ButtonMiddle
Space = _mirage_py.Space
Apostrophe = _mirage_py.Apostrophe
Comma = _mirage_py.Comma
Minus = _mirage_py.Minus
Period = _mirage_py.Period
Slash = _mirage_py.Slash
D0 = _mirage_py.D0
D1 = _mirage_py.D1
D2 = _mirage_py.D2
D3 = _mirage_py.D3
D4 = _mirage_py.D4
D5 = _mirage_py.D5
D6 = _mirage_py.D6
D7 = _mirage_py.D7
D8 = _mirage_py.D8
D9 = _mirage_py.D9
Semicolon = _mirage_py.Semicolon
Equal = _mirage_py.Equal
A = _mirage_py.A
B = _mirage_py.B
C = _mirage_py.C
D = _mirage_py.D
E = _mirage_py.E
F = _mirage_py.F
G = _mirage_py.G
H = _mirage_py.H
I = _mirage_py.I
J = _mirage_py.J
K = _mirage_py.K
L = _mirage_py.L
M = _mirage_py.M
N = _mirage_py.N
O = _mirage_py.O
P = _mirage_py.P
Q = _mirage_py.Q
R = _mirage_py.R
S = _mirage_py.S
T = _mirage_py.T
U = _mirage_py.U
V = _mirage_py.V
W = _mirage_py.W
X = _mirage_py.X
Y = _mirage_py.Y
Z = _mirage_py.Z
LeftBracket = _mirage_py.LeftBracket
Backslash = _mirage_py.Backslash
RightBracket = _mirage_py.RightBracket
GraveAccent = _mirage_py.GraveAccent
World1 = _mirage_py.World1
World2 = _mirage_py.World2
Escape = _mirage_py.Escape
Enter = _mirage_py.Enter
Tab = _mirage_py.Tab
Backspace = _mirage_py.Backspace
Insert = _mirage_py.Insert
Delete = _mirage_py.Delete
Right = _mirage_py.Right
Left = _mirage_py.Left
Down = _mirage_py.Down
Up = _mirage_py.Up
PageUp = _mirage_py.PageUp
PageDown = _mirage_py.PageDown
Home = _mirage_py.Home
End = _mirage_py.End
CapsLock = _mirage_py.CapsLock
ScrollLock = _mirage_py.ScrollLock
NumLock = _mirage_py.NumLock
PrintScreen = _mirage_py.PrintScreen
Pause = _mirage_py.Pause
F1 = _mirage_py.F1
F2 = _mirage_py.F2
F3 = _mirage_py.F3
F4 = _mirage_py.F4
F5 = _mirage_py.F5
F6 = _mirage_py.F6
F7 = _mirage_py.F7
F8 = _mirage_py.F8
F9 = _mirage_py.F9
F10 = _mirage_py.F10
F11 = _mirage_py.F11
F12 = _mirage_py.F12
F13 = _mirage_py.F13
F14 = _mirage_py.F14
F15 = _mirage_py.F15
F16 = _mirage_py.F16
F17 = _mirage_py.F17
F18 = _mirage_py.F18
F19 = _mirage_py.F19
F20 = _mirage_py.F20
F21 = _mirage_py.F21
F22 = _mirage_py.F22
F23 = _mirage_py.F23
F24 = _mirage_py.F24
F25 = _mirage_py.F25
KP0 = _mirage_py.KP0
KP1 = _mirage_py.KP1
KP2 = _mirage_py.KP2
KP3 = _mirage_py.KP3
KP4 = _mirage_py.KP4
KP5 = _mirage_py.KP5
KP6 = _mirage_py.KP6
KP7 = _mirage_py.KP7
KP8 = _mirage_py.KP8
KP9 = _mirage_py.KP9
KPDecimal = _mirage_py.KPDecimal
KPDivide = _mirage_py.KPDivide
KPMultiply = _mirage_py.KPMultiply
KPSubtract = _mirage_py.KPSubtract
KPAdd = _mirage_py.KPAdd
KPEnter = _mirage_py.KPEnter
KPEqual = _mirage_py.KPEqual
LeftShift = _mirage_py.LeftShift
LeftControl = _mirage_py.LeftControl
LeftAlt = _mirage_py.LeftAlt
LeftSuper = _mirage_py.LeftSuper
RightShift = _mirage_py.RightShift
RightControl = _mirage_py.RightControl
RightAlt = _mirage_py.RightAlt
RightSuper = _mirage_py.RightSuper
Menu = _mirage_py.Menu
class InputPoint(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_mirage_py.InputPoint_x_get, _mirage_py.InputPoint_x_set)
    y = property(_mirage_py.InputPoint_y_get, _mirage_py.InputPoint_y_set)

    def __init__(self):
        _mirage_py.InputPoint_swiginit(self, _mirage_py.new_InputPoint())
    __swig_destroy__ = _mirage_py.delete_InputPoint

# Register InputPoint in _mirage_py:
_mirage_py.InputPoint_swigregister(InputPoint)
class ScrollOffset(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_mirage_py.ScrollOffset_x_get, _mirage_py.ScrollOffset_x_set)
    y = property(_mirage_py.ScrollOffset_y_get, _mirage_py.ScrollOffset_y_set)

    def __init__(self):
        _mirage_py.ScrollOffset_swiginit(self, _mirage_py.new_ScrollOffset())
    __swig_destroy__ = _mirage_py.delete_ScrollOffset

# Register ScrollOffset in _mirage_py:
_mirage_py.ScrollOffset_swigregister(ScrollOffset)

def IsMouseButtonPressed(eMouseButton):
    return _mirage_py.IsMouseButtonPressed(eMouseButton)

def IsKeyPressed(eKeyValue):
    return _mirage_py.IsKeyPressed(eKeyValue)

def IsKeyRepeated(eKeyValue):
    return _mirage_py.IsKeyRepeated(eKeyValue)

def GetCursorPoint(rCursorPoint):
    return _mirage_py.GetCursorPoint(rCursorPoint)

def GetSrollOffset(rSrollOffset):
    return _mirage_py.GetSrollOffset(rSrollOffset)

def CreateInputPoint(x, y):
    point = InputPoint()
    point.x = x
    point.y = y
    return point

def CreateScrollOffset(x, y):
    offset = ScrollOffset()
    offset.x = x
    offset.y = y
    return offset

MIRAGE_LOG_TAG = _mirage_py.MIRAGE_LOG_TAG

def MRG_CONFIG_LOG(*args):
    return _mirage_py.MRG_CONFIG_LOG(*args)

def LOGV(*args):
    return _mirage_py.LOGV(*args)

def LOGI(*args):
    return _mirage_py.LOGI(*args)

def LOGD(*args):
    return _mirage_py.LOGD(*args)

def LOGE(*args):
    return _mirage_py.LOGE(*args)

def LOGA(*args):
    return _mirage_py.LOGA(*args)
class MeshFilter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, spHandle):
        _mirage_py.MeshFilter_swiginit(self, _mirage_py.new_MeshFilter(spHandle))
    __swig_destroy__ = _mirage_py.delete_MeshFilter

    def LoadMesh(self, svMeshPath, bIsStatic=True):
        return _mirage_py.MeshFilter_LoadMesh(self, svMeshPath, bIsStatic)

    def CreateMesh(self, rVertexes, rVertexIndexes, bIsStatic=True):
        return _mirage_py.MeshFilter_CreateMesh(self, rVertexes, rVertexIndexes, bIsStatic)

    def CountMeshVertexes(self):
        return _mirage_py.MeshFilter_CountMeshVertexes(self)

    def SetMeshColor(self, *args):
        return _mirage_py.MeshFilter_SetMeshColor(self, *args)

    def SetVertexBoneMaps(self, rVertexBoneMaps):
        return _mirage_py.MeshFilter_SetVertexBoneMaps(self, rVertexBoneMaps)

# Register MeshFilter in _mirage_py:
_mirage_py.MeshFilter_swigregister(MeshFilter)
cvar = _mirage_py.cvar

class Object(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, svName):
        _mirage_py.Object_swiginit(self, _mirage_py.new_Object(svName))
    __swig_destroy__ = _mirage_py.delete_Object

    def GetLayer(self):
        return _mirage_py.Object_GetLayer(self)

    def SetLayer(self, uLayer):
        return _mirage_py.Object_SetLayer(self, uLayer)

    def GetName(self):
        return _mirage_py.Object_GetName(self)

    def SetName(self, svName):
        return _mirage_py.Object_SetName(self, svName)

    def IsMaskEnabled(self):
        return _mirage_py.Object_IsMaskEnabled(self)

    def EnableMask(self):
        return _mirage_py.Object_EnableMask(self)

    def DisableMask(self):
        return _mirage_py.Object_DisableMask(self)

# Register Object in _mirage_py:
_mirage_py.Object_swigregister(Object)
class Observer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.Observer_swiginit(self, _mirage_py.new_Observer())
    __swig_destroy__ = _mirage_py.delete_Observer

    def SetDepth(self, uDepth):
        return _mirage_py.Observer_SetDepth(self, uDepth)

    def SetCullingMask(self, uMask):
        return _mirage_py.Observer_SetCullingMask(self, uMask)

    def SetView(self, rFocusVec, rTopVec):
        return _mirage_py.Observer_SetView(self, rFocusVec, rTopVec)

    def SetProjection(self, fFovDegree, fAspectRatio, fNearClip, fFarClip):
        return _mirage_py.Observer_SetProjection(self, fFovDegree, fAspectRatio, fNearClip, fFarClip)

    def EnableOrthoView(self, fLeft, fRight, fTop, fBottom, fNear, fFar):
        return _mirage_py.Observer_EnableOrthoView(self, fLeft, fRight, fTop, fBottom, fNear, fFar)

    def SetPosition(self, rPosition):
        return _mirage_py.Observer_SetPosition(self, rPosition)

    def SetClearFlag(self, uClearFlag):
        return _mirage_py.Observer_SetClearFlag(self, uClearFlag)

    def GetPosition(self):
        return _mirage_py.Observer_GetPosition(self)

    def Rotate(self, rRotAxisVec, fDegree):
        return _mirage_py.Observer_Rotate(self, rRotAxisVec, fDegree)

    def GetRotation(self):
        return _mirage_py.Observer_GetRotation(self)

    def ClearView(self):
        return _mirage_py.Observer_ClearView(self)

# Register Observer in _mirage_py:
_mirage_py.Observer_swigregister(Observer)
class Text(Model):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _mirage_py.Text_swiginit(self, _mirage_py.new_Text())
    __swig_destroy__ = _mirage_py.delete_Text

    def SetLayer(self, uLayer):
        return _mirage_py.Text_SetLayer(self, uLayer)

    def SetFontSize(self, uFontSize):
        return _mirage_py.Text_SetFontSize(self, uFontSize)

    def GetFontSize(self):
        return _mirage_py.Text_GetFontSize(self)

    def SetSize(self, fWidth, fHeight):
        return _mirage_py.Text_SetSize(self, fWidth, fHeight)

    def SetText(self, svText):
        return _mirage_py.Text_SetText(self, svText)

    def SetScale(self, rScale):
        return _mirage_py.Text_SetScale(self, rScale)

    def SetPosition(self, rPosition, bOnOverlay=False):
        return _mirage_py.Text_SetPosition(self, rPosition, bOnOverlay)

    def SetFont(self, svFontPath):
        return _mirage_py.Text_SetFont(self, svFontPath)

    def SetColor(self, *args):
        return _mirage_py.Text_SetColor(self, *args)

    def GetWidth(self):
        return _mirage_py.Text_GetWidth(self)

    def GetHeight(self):
        return _mirage_py.Text_GetHeight(self)

    def GetPitch(self):
        return _mirage_py.Text_GetPitch(self)

    def GetScanline(self):
        return _mirage_py.Text_GetScanline(self)

    def Configure(self, *args):
        return _mirage_py.Text_Configure(self, *args)

    def IsDepthEnabled(self):
        return _mirage_py.Text_IsDepthEnabled(self)

    def SetDepthStatus(self, bEnable):
        return _mirage_py.Text_SetDepthStatus(self, bEnable)

    def Refresh(self):
        return _mirage_py.Text_Refresh(self)

# Register Text in _mirage_py:
_mirage_py.Text_swigregister(Text)
class Transform(Component):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, spHandle):
        _mirage_py.Transform_swiginit(self, _mirage_py.new_Transform(spHandle))
    __swig_destroy__ = _mirage_py.delete_Transform

    def GetPosition(self):
        return _mirage_py.Transform_GetPosition(self)

    def GetRotation(self):
        return _mirage_py.Transform_GetRotation(self)

    def GetScale(self):
        return _mirage_py.Transform_GetScale(self)

    def SetPosition(self, rPos):
        return _mirage_py.Transform_SetPosition(self, rPos)

    def SetRotation(self, rRot):
        return _mirage_py.Transform_SetRotation(self, rRot)

    def SetScale(self, rScale):
        return _mirage_py.Transform_SetScale(self, rScale)

    def Rotate(self, rRotVec, fDegree):
        return _mirage_py.Transform_Rotate(self, rRotVec, fDegree)

# Register Transform in _mirage_py:
_mirage_py.Transform_swigregister(Transform)
class ThreadPool(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, uThreadNum):
        _mirage_py.ThreadPool_swiginit(self, _mirage_py.new_ThreadPool(uThreadNum))
    __swig_destroy__ = _mirage_py.delete_ThreadPool

# Register ThreadPool in _mirage_py:
_mirage_py.ThreadPool_swigregister(ThreadPool)
class Animation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, spData):
        _mirage_py.Animation_swiginit(self, _mirage_py.new_Animation(spData))
    __swig_destroy__ = _mirage_py.delete_Animation

    def LoadClipFromFile(self, svFilePath, svAliasName):
        return _mirage_py.Animation_LoadClipFromFile(self, svFilePath, svAliasName)

    def Play(self, svClipName):
        return _mirage_py.Animation_Play(self, svClipName)

    def SetDuration(self, svClipName, fDuration):
        return _mirage_py.Animation_SetDuration(self, svClipName, fDuration)

    def GetCurrClipName(self):
        return _mirage_py.Animation_GetCurrClipName(self)

# Register Animation in _mirage_py:
_mirage_py.Animation_swigregister(Animation)

